### ISSUE TITLE
Homepage on Github Pages empty

### ISSUE THREAD

**Issue by jnutz** [chesterhow/tale#20]
I'm just trying to switch from Jekyll's default theme to tale.  But my homepage is empty on Github Pages despite it working without any errors on local PC.  

My Gemfile
```ruby
source "https://rubygems.org"
gem "tale"
gem "github-pages", group: :jekyll_plugins
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.6"
end
gem "tzinfo-data", platforms: [:mingw, :mswin, :x64_mingw, :jruby]
```

**Comment by chesterhow** [comment]
Did you enable GitHub pages in your repository's settings?

**Comment by chesterhow** [comment]
My bad. I've figured out the problem. For hosting on GitHub pages the setup is slightly different. I've updated the README with a new installation guide for those who plan to host on GitHub Pages. DO try it out and let me know if you face any other issues 😄

**Comment by jnutz** [comment]
Sorry but I'm still experiencing the same problem after following the new instructions for Github.  It's working locally but not on Github pages.

And yes it's Github pages is enabled:
![image](https://user-images.githubusercontent.com/1831655/35474325-b6ac860c-03c7-11e8-9e84-fb4864dd73d7.png)

**Comment by chesterhow** [comment]
I took a look at your repository and I think I found the issue. I'm assuming you followed the new instructions for the Ruby Gem method? This method only works for self-hosted sites. Since you're hosting it on GitHub Pages, the setting up is slightly different. You'll need to use the [GitHub Pages method](https://github.com/chesterhow/tale#github-pages-method) instead. Hope this solves your issue 😄

**Comment by jnutz** [comment]
Actually, I followed the new Github pages method pages (as you can see from the _config.ml file).  Is there something that you saw which you think I did wrong?

**Comment by chesterhow** [comment]
Just to double check, this is your repository right? https://github.com/jnutz/jnutz.github.io

In your `Gemfile` you seem to be missing these 2 lines:
```
gem "jekyll-remote-theme"
gem "jekyll-paginate"
```

In your `_config.yml` you should remove this line:
```yaml
theme: tale
```
and add these lines
```yaml
remote_theme: chesterhow/tale

plugins:
  - jekyll-paginate
  - jekyll-remote-theme
```

Did you by any chance forget to push your latest commit?

**Comment by jnutz** [comment]
Indeed that was the mistake I made (something wrong with my git client that I just fixed), sorry about that!  

Yes it's working now, thank you for your help!

**Comment by chesterhow** [comment]
You're most welcome! Glad to know that its working 😄
